repos:
  # Standard pre-commit checks.
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace

  # ament_* code linters and checks
  - repo: local
    hooks:
      # Style code analysis ------------------------------------------------------------------------
      - id: ament_black
        name: ament_black
        entry: ament_black
        args: ["--reformat"]
        language: system
        types: [python]

  - repo: local
    hooks:
      - id: ament_uncrustify
        name: ament_uncrustify
        entry: ament_uncrustify
        args: ["--reformat"]
        language: system
        # TODO(Nacho): Fix this crap
        exclude: "flat_hash_map.hpp$"
        types: [c++]

      # Static code analysis ----------------------------------------------------------------------
      - id: ament_lint_cmake
        name: ament_lint_cmake
        entry: ament_lint_cmake
        types: [cmake]
        language: system

      - id: ament_flake8
        name: ament_flake8
        entry: ament_flake8
        language: system
        types: [python]

      - id: ament_pep257
        name: ament_pep257
        entry: ament_pep257
        language: system
        types: [python]

      - id: ament_xmllint
        name: ament_xmllint
        entry: ament_xmllint
        types: [xml]
        language: system
