name: 'Tailscale SSH'
description: 'Join tailnet in SSH mode for debugging'
branding:
  icon: terminal

inputs:
  ssh-wait-minutes:
    required: false
    type: number
    default: 10
    description: Number of minutes to wait for SSH connection at end of workflow before timing out
  ts-authkey:
    required: true
    description: Tailscale authkey

runs:
  using: 'composite'
  steps:
    - name: Start tailscale
      uses: tailscale/github-action@v2
      with:
        authkey: ${{ inputs.ts-authkey }}
        tags: tag:ci-builder
        args: --ssh
    - name: Show connection command
      shell: bash
      run: |
        echo -e "::notice::\u001b[102mREADME: SSH Connection instructions"
        echo -e "::notice::\u001b[92mTo connect using SSH, run the following from inside the tailnet:"
        echo -e "::notice::\u001b[92m  ssh runner@github-$HOSTNAME"
        echo -e "::notice::\u001b[92mYour tailscale user must be in group:developers"

    - name: Wait for SSH sessions
      uses: botsandus/github-actions/tailscale-ssh/wait-sessions@TECH-149-Add-SSH-debug
      with:
        tail-log: /home/runner/tailscaled.log
        wait-minutes: ${{ inputs.ssh-wait-minutes }}
