name: 'Tailscale SSH'
description: 'Join tailnet in SSH mode for debugging'
branding:
  icon: terminal

inputs:
  ssh-wait-minutes:
    required: false
    type: number
    default: 10
    description: Number of minutes to wait for SSH connections at end of job
  ts-authkey:
    required: false
    description: Deprecated: Ignored by implementation

runs:
  using: 'composite'
  steps:
    - name: Calculate values
      id: vars
      shell: bash
      run: echo "hostname=github-${{github.event.repository.name}}-${{github.run_number}}-${{github.run_attempt}}" >> "$GITHUB_OUTPUT"

    - name: Start tailscale
      uses: tailscale/github-action@v2
      with:
        oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
        oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
        tags: tag:ci-builder
        args: --ssh --operator=runner --hostname=${{steps.vars.outputs.hostname}}

    - name: Show connection command
      shell: bash
      run: |
        [[ -n '${{ inputs.ts-authkey }}' ]] \
          && echo "::warning:: inputs.ts-authkey is deprecated for botsandus/github-actions/tailscale-ssh"

        echo -en "::warning title=SSH Debugging Enabled::\u001b[44m\u001b[37mSSH Debugging Enabled%0A"
        echo -en "\u001b[92mTo connect using SSH, run the following from inside the tailnet:%0A"
        echo -en "\u001b[92m  ssh runner@${{steps.vars.outputs.hostname}}%0A"
        echo -en "\u001b[92mYour tailscale user must be in group:developers\n"

    # The following step must be a "post" action to allow flow to continue
    # after SSH is setup.  This also means that the output is at the end of the
    # job, where it is visible to the user.  Unfortunately, composite actions
    # don't support post steps and the current github actions on Marketplace
    # that run bash script in post don't support cancellation, hence this had
    # to be implemented in javascript.  As we want to use the off-the-shelf
    # tailscale action to avoid overhead and javascript actions can't call
    # other actions, this had to be implemented as a separate action.  If any
    # of this changes in the future, the action can be simplified.
    - name: Wait for SSH sessions
      uses: botsandus/github-actions/wait-sessions@master
      with:
        tail-log: /home/runner/tailscaled.log
        wait-minutes: ${{ inputs.ssh-wait-minutes }}
        on-exit: '["/usr/bin/tailscale", "logout"]'
