name: "Session wait"
description: "Wait for login sessions to terminate"

inputs:
  tail-log:
    description: "Log file to tail - disabled if not set"
    required: false
  session-exe:
    description: "Executable indicating that sessions are still running"
    required: false
    default: "login"
  wait-minutes:
    description: "Number of minutes to wait for sessions to be established, default 10"
    type: number
    required: false
  check-period:
    description: "Number of seconds between checks for sessions, default 10"
    type: number
    required: false
  status-period:
    description: "Number of seconds between status reports while waiting for sessions, default 5 minutes"
    type: number
    required: false
  on-exit:
    description: "Program and arguments to execute on exit (e.g. to cleanup resource) as JSON array of strings"
    required: false

runs:
  using: "node20"
  main: "dist/main/index.js"
  post: "dist/post/index.js"
  post-if: "!cancelled()"
