# This workflow will build a Docker container, including running any tests which
# are part of the build process.
#
# If the workflow is triggered as part of an explicit dispatch, pull request, or
# push to master/main then the image will also be pushed to ECR.

name: Container build

on:
  workflow_call:
    inputs:
      ecrRepo:
        required: true
        type: string
        description: The path of the ECR repository to use
      dockerfile:
        required: false
        type: string
        default: Dockerfile
        description: The path of the Dockerfile to use, relative to the root

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout with submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive
          token: ${{ secrets.GIT_CHECKOUT_PAT }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.ECR_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.ECR_AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2
          mask-aws-account-id: false

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Create docker builder
        id: create-builder
        run: |
          BUILDER_NAME=github-actions-builder-${GITHUB_SHA}-${{ github.run_number }}
          docker buildx create --use --name $BUILDER_NAME
          echo "::set-output name=name::$BUILDER_NAME"

      - name: Build and push image
        run: |
          DOCKER_BUILDKIT=1
          REPO=${{ steps.login-ecr.outputs.registry }}/${{ inputs.ecrRepo }}
          BRANCH=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}
          BRANCH=${BRANCH//[^a-zA-Z0-9\-]/\-} # Strip any invalid characters

          # Work out all of the tags we will use
          COMMIT_TAG=$REPO:${GITHUB_SHA}
          BUILD_TAG=$REPO:build-${{ github.run_number }}
          BUILD_BRANCH_TAG=$REPO:${BRANCH}-build-${{ github.run_number }}
          COMMIT_TAG=$REPO:${GITHUB_SHA}
          COMMIT_BRANCH_TAG=$REPO:${BRANCH}-${GITHUB_SHA}
          TAG_ARG="--tag $COMMIT_TAG --tag $BUILD_TAG --tag $BUILD_BRANCH_TAG --tag $COMMIT_BRANCH_TAG"

          # Add a push arg if we are going to push
          SHOULD_PUSH=${{ github.event_name == 'workflow_dispatch' || github.event_name == 'pull_request' || (github.event_name == 'push' && (github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main')) }}
          if [ $SHOULD_PUSH = true ]; then PUSH_ARG='--push'; else PUSH_ARG=''; fi

          docker buildx build --file ${{ inputs.dockerfile }} --build-arg GIT_CHECKOUT_PAT=${{ secrets.GIT_CHECKOUT_PAT }} $TAG_ARG $PUSH_ARG .

      - name: Teardown docker builder
        if: always()
        run: |
          docker buildx rm ${{ steps.create-builder.outputs.name }} || true

      - uses: act10ns/slack@v1
        if: always()
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          status:  ${{ job.status }}
          channel: '#notifications'
